drm/mediatek: fix implicit function declaration
When building mtk_drm_drv.o the following build error is seen:

../drivers/gpu/drm/mediatek/mtk_drm_drv.c: In function ‘mtk_drm_kms_init’:
../drivers/gpu/drm/mediatek/mtk_drm_drv.c:291:8: error: implicit declaration of
 function ‘dma_set_max_seg_size’; did you mean ‘drm_rect_adjust_size’? [-Werror=implicit-function-declaration]
  ret = dma_set_max_seg_size(dma_dev, (unsigned int)DMA_BIT_MASK(32));
        ^~~~~~~~~~~~~~~~~~~~
        drm_rect_adjust_size
../drivers/gpu/drm/mediatek/mtk_drm_drv.c:291:52: error: implicit declaration of
 function ‘DMA_BIT_MASK’; did you mean ‘BIT_MASK’? [-Werror=implicit-function-declaration]
  ret = dma_set_max_seg_size(dma_dev, (unsigned int)DMA_BIT_MASK(32));
                                                    ^~~~~~~~~~~~
                                                    BIT_MASK

Rework to add a missing include file 'linux/dma-mapping.h', because that
is the (only) header file containing that declaration.

Fixes: 070955558e82 ("drm/mediatek: set DMA max segment size")
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>